# Generated by Django 3.1.3 on 2021-04-01 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Courrier électronique')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Téléphone')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Prix')),
                ('available', models.BooleanField(default=True)),
                ('image_url', models.URLField(max_length=3000, verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name="Date d'ajout ")),
            ],
            options={
                'verbose_name': 'Fleur',
                'verbose_name_plural': 'Fleurs',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_date', models.DateField(auto_now_add=True, verbose_name='Date de réservation')),
                ('delivered', models.BooleanField(default=False, verbose_name='Livraison terminée')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.flower')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
            },
        ),
    ]
